before_script:
  - ./script/prepare_build.sh
  - ruby -v
  - gem install bundler
  - cp config/application.yml.example config/application.yml
  - cp config/secrets.yml.example config/secrets.yml
  - bundle --without postgres
  - RAILS_ENV=test bundle exec rake db:setup
specs:
  script: SIMPLECOV=true RAILS_ENV=test bundle exec rake spec
  tags:
    - ruby
    - mysql
rubocop:
  script: bundle exec rubocop
  tags:
    - ruby
    - mysql
brakeman:
  script: bundle exec brakeman
  tags:
    - ruby
    - mysql
